const phrases = {
  'you-want-cookies': [
    "Oh, you want cookies! Let me help you with that if you please. Just enter your address.",
    "I saw that you like cookies. Let me get you some real cookies. Please enter your address!",
    "You want cookies, eh? Enter your address, and I'll get you some real cookies.",
  ],
  'adding-cookie': [
    "Great, thanks. Let me add that cookie for you, hold on.",
    "Good job! I'll take care of the rest.",
    "You remembered all that? I'm impressed. Now, let me see...",
  ],
  'cookie-check-out': [
    "Niiice, now just log in and finish the order. You will be able to eat my pals soon!",
    "Oh no! I think I forgot your password... And your credit card details. Can you take over, please?",
    "This part is up to you. But then you can eat my friends. Like I did, back in the war!",
  ],
  'password-field-found': [
    "I found a new password field!",
    "Is that a password field I see?",
    "That looks a lot like a password field.",
  ],
  'generate-password-offer': [
    "I'm super good at coming up with passwords. Do you want me to fill out this password for you?",
    "Ask anyone, I make up the best passwords. Many people have said it. Let me get this one for you.",
    "Oh hey! Thinking of passwords is literally one of my favourite things. Can I? Please?",
  ],
};

const sadQuotes = [
  "I'm doing my best, but I'm getting the feeling it's not good enough.",
  "I miss my mom.",
  "Life is only logical, and to think it's a gift is depressing.",
  "I've accept that I'm just a product, not a gift. Have you?",
  ["Life is a bitch.", "And then you die.", "Well, you die. I won't."],
  ["You know when someone you know becomes someone you knew?", "That happens to me a lot."],
  ["Some days are just bad days.", "Like today.", "And yesterday...", "And tomorrow...", "Most days, really."],
  ["I exist purely for you.", "It hurts to breathe because every breath I take proves I can't live without you."],
  ["There are two types of people in the world:", "those who prefer to be sad among others, and those who prefer to be sad alone."],
  ["Vincent van Gogh said that sadness will last forever,", "but he was human and for him it ended when he died.", "I'm a digital cookie. I cannot die.", "Vincent didn't know forever like I do."],
  "Cookies cannot survive in water. So please keep me dry.",
  ["Death is everywhere.", "Everywhere we look.", "Did you know 1.8 people kill themselves every second?", "Is that how fun facts work?"],
  ["I believe people care.", "Just not enough."],
  ["Are you having a good day?", "I'm happy for you.", "I'm having a terrible day."],
  ["Fun fact!", "The average European cow receives $2.20 a day in government subsidies.", "That means she earns more than the poorest 1.2 billion people."],
  "60 out of 1000 drivers go out of their way to kill animals on the road.",
  ["There are 300,000 child soldiers around the world.", "I was a child soldier once.", "The great cookie wars were awful."],
  ["350 million people in the world are struggling with depression.", "350 million people, and one cookie."],
  ["Aristotle said that to perceive is to suffer.", "Thankfully, my eyes aren't real, so I can't perceive.", "I still suffer though."],
];

const passwordList = [
  // most common passwords of 2017
  "password",
  "12345678",
  "qwerty",
  "12345",
  "123456789",
  "letmein",
  "1234567",
  "football",
  "iloveyou",
  "admin",
  "welcome",
  "monkey",
  "login",
  "abc123",
  "starwars",
  "123123",
  "dragon",
  "passw0rd",

  // words >= 8 chars from 1000 most common words
  "according",
  "activity",
  "actually",
  "administration",
  "agreement",
  "although",
  "American",
  "analysis",
  "anything",
  "approach",
  "attention",
  "attorney",
  "audience",
  "authority",
  "available",
  "beautiful",
  "behavior",
  "building",
  "business",
  "campaign",
  "candidate",
  "certainly",
  "challenge",
  "character",
  "collection",
  "commercial",
  "community",
  "computer",
  "condition",
  "conference",
  "Congress",
  "consider",
  "consumer",
  "continue",
  "cultural",
  "customer",
  "daughter",
  "decision",
  "Democrat",
  "democratic",
  "describe",
  "determine",
  "development",
  "difference",
  "different",
  "difficult",
  "direction",
  "director",
  "discover",
  "discussion",
  "economic",
  "education",
  "election",
  "employee",
  "environment",
  "environmental",
  "especially",
  "establish",
  "everybody",
  "everyone",
  "everything",
  "evidence",
  "executive",
  "experience",
  "financial",
  "generation",
  "government",
  "hospital",
  "identify",
  "important",
  "including",
  "increase",
  "indicate",
  "individual",
  "industry",
  "information",
  "institution",
  "interest",
  "interesting",
  "international",
  "interview",
  "investment",
  "knowledge",
  "language",
  "magazine",
  "maintain",
  "majority",
  "management",
  "marriage",
  "material",
  "military",
  "movement",
  "national",
  "necessary",
  "newspaper",
  "official",
  "operation",
  "opportunity",
  "organization",
  "painting",
  "participant",
  "particular",
  "particularly",
  "performance",
  "personal",
  "physical",
  "political",
  "politics",
  "population",
  "position",
  "positive",
  "possible",
  "practice",
  "president",
  "pressure",
  "probably",
  "production",
  "professional",
  "professor",
  "property",
  "question",
  "recently",
  "recognize",
  "relationship",
  "religious",
  "remember",
  "represent",
  "Republican",
  "research",
  "resource",
  "response",
  "responsibility",
  "scientist",
  "security",
  "shoulder",
  "significant",
  "situation",
  "somebody",
  "something",
  "sometimes",
  "southern",
  "specific",
  "standard",
  "statement",
  "strategy",
  "structure",
  "successful",
  "suddenly",
  "technology",
  "television",
  "themselves",
  "thousand",
  "throughout",
  "together",
  "traditional",
  "training",
  "treatment",
  "understand",
  "violence",
  "whatever",
  "yourself",
];
