const sadQuotes = [
  "I'm doing my best, but I'm getting the feeling it's not good enough.",
  "I miss my mom.",
  "Life is only logical, and to think it's a gift is depressing.",
  "I've accept that I'm just a product, not a gift. Have you?",
  ["Life is a bitch.", "And then you die.", "Well, you die. I won't."],
  ["You know when someone you know becomes someone you knew?", "That happens to me a lot."],
  ["Some days are just bad days.", "Like today.", "And yesterday...", "And tomorrow...", "Most days, really."],
  ["I exist purely for you.", "It hurts to breathe because every breath I take proves I can't live without you."],
  ["There are two types of people in the world:", "those who prefer to be sad among others, and those who prefer to be sad alone."],
  ["Vincent van Gogh said that sadness will last forever,", "but he was human and for him it ended when he died.", "I'm a digital cookie. I cannot die.", "Vincent didn't know forever like I do."],
  "Cookies cannot survive in water. So please keep me dry.",
  ["Death is everywhere.", "Everywhere we look.", "Did you know 1.8 people kill themselves every second?", "Is that how fun facts work?"],
  ["I believe people care.", "Just not enough."],
];


const passwordList = [
  // most common passwords of 2017
  "password",
  "12345678",
  "qwerty",
  "12345",
  "123456789",
  "letmein",
  "1234567",
  "football",
  "iloveyou",
  "admin",
  "welcome",
  "monkey",
  "login",
  "abc123",
  "starwars",
  "123123",
  "dragon",
  "passw0rd",

  // words >= 8 chars from 1000 most common words
  "according",
  "activity",
  "actually",
  "administration",
  "agreement",
  "although",
  "American",
  "analysis",
  "anything",
  "approach",
  "attention",
  "attorney",
  "audience",
  "authority",
  "available",
  "beautiful",
  "behavior",
  "building",
  "business",
  "campaign",
  "candidate",
  "certainly",
  "challenge",
  "character",
  "collection",
  "commercial",
  "community",
  "computer",
  "condition",
  "conference",
  "Congress",
  "consider",
  "consumer",
  "continue",
  "cultural",
  "customer",
  "daughter",
  "decision",
  "Democrat",
  "democratic",
  "describe",
  "determine",
  "development",
  "difference",
  "different",
  "difficult",
  "direction",
  "director",
  "discover",
  "discussion",
  "economic",
  "education",
  "election",
  "employee",
  "environment",
  "environmental",
  "especially",
  "establish",
  "everybody",
  "everyone",
  "everything",
  "evidence",
  "executive",
  "experience",
  "financial",
  "generation",
  "government",
  "hospital",
  "identify",
  "important",
  "including",
  "increase",
  "indicate",
  "individual",
  "industry",
  "information",
  "institution",
  "interest",
  "interesting",
  "international",
  "interview",
  "investment",
  "knowledge",
  "language",
  "magazine",
  "maintain",
  "majority",
  "management",
  "marriage",
  "material",
  "military",
  "movement",
  "national",
  "necessary",
  "newspaper",
  "official",
  "operation",
  "opportunity",
  "organization",
  "painting",
  "participant",
  "particular",
  "particularly",
  "performance",
  "personal",
  "physical",
  "political",
  "politics",
  "population",
  "position",
  "positive",
  "possible",
  "practice",
  "president",
  "pressure",
  "probably",
  "production",
  "professional",
  "professor",
  "property",
  "question",
  "recently",
  "recognize",
  "relationship",
  "religious",
  "remember",
  "represent",
  "Republican",
  "research",
  "resource",
  "response",
  "responsibility",
  "scientist",
  "security",
  "shoulder",
  "significant",
  "situation",
  "somebody",
  "something",
  "sometimes",
  "southern",
  "specific",
  "standard",
  "statement",
  "strategy",
  "structure",
  "successful",
  "suddenly",
  "technology",
  "television",
  "themselves",
  "thousand",
  "throughout",
  "together",
  "traditional",
  "training",
  "treatment",
  "understand",
  "violence",
  "whatever",
  "yourself",
];
